name: CI/CD pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  unit:
    name: run unit test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Run unit test
        working-directory: server
        run: npm run test:unit

      - name: Code coveratge Thresholds
        working-directory: server
        run: npm run test:unit:coverage

  integration:
    name: run integration test
    runs-on: ubuntu-latest
    needs: unit
    if: github.event.name == 'pull_request' && github.event.pull_request.base.ref == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Run integration tests
        working-directory: server
        run: npm run test:integration
