name: CI/CD pipeline

on:
  push:
    branches: [main]

  pull:
    branches: [main]

jobs:
  ci:
    name: run test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Run unit test
        working-directory: server
        run: npm run test

      - name: Code coveratge Thresholds
        working-directory: server
        run: npm run test:coverage
